#!/bin/sh -e
# set -x

SETUP_SSH_KEY_COPY=/ssh/id_rsa
SETUP_SERVER_KEY_COPY=/tls/server.key

echo "Waiting to begin nginx setup..."
for i in `seq 1 30`
do
    if [ -f "$SETUP_SSH_KEY_COPY" ] && [ -f "$SETUP_SERVER_KEY_COPY" ] ; then
    	echo "Setting up nginx..."
    	/nginx/setup-nginx
    	echo "Starting nginx..."
    	nginx -g 'daemon off;'
	fi
    sleep 1
done

>&2 echo "Error! Setup did not complete successfully!"
exit 1