#!/bin/sh -e
# set -x

cp -rf /tls /etc/nginx
cp -rf /nginx /etc

DEFAULT_SERVER_CONFIG_REPOS="https://github.com/okwolf/php-hello-world-config.git"
mkdir -p /config/nginx
for REMOTE_REPO_PATH in "${DOCKER_SERVER_CONFIG_REPOS:=$DEFAULT_SERVER_CONFIG_REPOS}"
do
  REMOTE_REPO_NAME=$(basename "$REMOTE_REPO_PATH" .git)
  LOCAL_REPO_PATH="/config/nginx/$REMOTE_REPO_NAME"
  /common-scripts/get-repo $REMOTE_REPO_PATH $LOCAL_REPO_PATH
  cp -rf $LOCAL_REPO_PATH/* /etc/nginx
done