#!/bin/sh -e
# set -x

apk add --no-cache git openssh

mkdir -p ~/.ssh
cp -r /ssh/* ~/.ssh
KNOWN_HOSTS=~/.ssh/known_hosts
rm -f $KNOWN_HOSTS

WEB_ROOT=/var/www/html
cp -r /www/* $WEB_ROOT

for REMOTE_REPO_PATH in $DOCKER_SERVER_WEB_REPOS
do
	REMOTE_REPO_SSH=$(echo "$REMOTE_REPO_PATH" | cut -d ":" -f 1)
	REMOTE_REPO_DOMAIN=$(echo "$REMOTE_REPO_SSH" | cut -d "@" -f 2)
	REMOTE_REPO_NAME=$(basename "$REMOTE_REPO_PATH" .git)
	LOCAL_REPO_PATH="$WEB_ROOT/$REMOTE_REPO_NAME"
	ssh-keyscan -H $REMOTE_REPO_DOMAIN > $KNOWN_HOSTS
	if ssh -T $REMOTE_REPO_SSH ; then
		if [ -d "$LOCAL_REPO_PATH" ] ; then
			cd $LOCAL_REPO_PATH && git pull
		else
			git clone --progress --depth 1 $REMOTE_REPO_PATH $LOCAL_REPO_PATH
		fi
	else
		SSH_PUBLIC_KEY=$(cat ~/.ssh/id_rsa.pub)
		>&2 echo "Error! Please add the following key to $REMOTE_REPO_DOMAIN: $SSH_PUBLIC_KEY"
		exit 1
	fi
done

cp -rf /nginx /etc